### ISSUE TITLE
how to insert data ?

### ISSUE THREAD

**Issue by black-eyes** [Azimul-Haque/easySchool#2]
hello, how can I insert data if I would like to try the app ??

**Comment by Azimul-Haque** [comment]
Well, you need to create a database in phpmyadmin mysql panel, then you need to migrate the database, create a test user. Then you can insert data.

**Comment by black-eyes** [comment]
Hello, I did that but I get sum errors can you sher with me  .sql file ?

**Comment by black-eyes** [comment]
Hello, Can you share with us the .sql file?

**Comment by Azimul-Haque** [comment]
Provide your email address, I will send the .sql file.

**Comment by black-eyes** [comment]
ayoubnaimi1993@gmail.com , thank you .
